---
- name: BIG-IP SETUP
  hosts: all
  connection: local
  gather_facts: false

  tasks:

  - name: CREATE NODES
    bigip_node:
      host: "{{hostvars[item].ansible_host}}"
      name: "{{hostvars[item].inventory_hostname}}"
      validate_certs: "no"
    loop: "{{ groups['webservers'] }}"

  - name: CREATE POOL
    bigip_pool:
      name: "http_pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
      validate_certs: "no"

  - name: ADD POOL MEMBERS
    bigip_pool_member:
      state: "present"
      name: "{{hostvars[item].inventory_hostname}}"
      host: "{{hostvars[item].ansible_host}}"
      port: "80"
      pool: "http_pool"
      validate_certs: "no"
    loop: "{{ groups['webservers'] }}"

  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      name: "vip"
      destination: "{{private_ip}}"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "http_pool"
      snat: "Automap"
      validate_certs: "no"

- name: BIG-IP SETUP
  hosts: all
  connection: local
  gather_facts: false

  vars:
   irules: ['irule1','irule2']
   
  tasks:

  - name: ADD iRules
    bigip_irule:
      module: "ltm"
      name: "{{item}}"
      content: "{{lookup('file','{{item}}')}}"
    with_items: "{{irules}}"
    
  - name: ATTACH iRules TO VIRTUAL SERVER
    bigip_virtual_server:
      name: "vip"
      irules: "{{irules}}"
